# Generated by Django 2.2.3 on 2019-07-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
