# Generated by Django 2.2.3 on 2019-07-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20190731_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
